### PR TITLE
[d3d9] Properly wait for texture mapping buffers

### LINKED ISSUE #247: [Regression] GTA IV - Frogged textures
Commit f90163b broke GTA IV's textures, Alt+Tab-ing out and back also makes the textures look completely different every single time. Reverting this commit fixes the issue.

Screenshot_20190717_135451

Screenshot_20190717_135539

### Software information
Grand Theft Auto IV

### System information
- GPU: RX 580 4GB
- Driver: Mesa ACO Git, AMDVLK 2019.Q3.2
- Wine version: Proton-4.11-GE-1
- D9VK version: 3e36478

### Apitrace file(s)
- [Same trace that can be found in issue #99](https://mega.nz/#!DEFnDQLI!G0fkUFzyZSvxbImQbB8xsSFNTX4bt_IWPoOXfbUalG8)

### Log files
- [GTAIV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3401745/GTAIV_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #247 

You can use sysmem textures as the source for copy operations and we should avoid rewriting the texture data while a copy is happening.

### CODE REVIEW

File: src/d3d9/d3d9_device.cpp [hunk 1]
```diff
@@ -3705,12 +3701,10 @@ namespace dxvk {
       // that cannot get affected by GPU, therefore readonly is A-OK for NOT waiting.
       const bool noOverwrite  = Flags & D3DLOCK_NOOVERWRITE;
       const bool readOnly     = Flags & D3DLOCK_READONLY;
-      const bool gpuImmutable = (readOnly && managed) || scratch || (systemmem && !modified);
```
Comment (Joshua-Ashton) [inline src/d3d9/d3d9_device.cpp]: The read only rule only applies to managed here.

Just get rid of the `(systemmem && !modified)` bit.

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp]: Does it?

Either way, we also need to wait for scratch as it can also be locked and copied.

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_device.cpp]: > Because of this, these resources cannot be accessed by the Direct3D device nor set as textures or render target

They will never be accessed by the CS thread? Unless there's an edgecase I am not considering.

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp]: > However, these resources can always be created, locked, and copied.

We do implement copying using the GPU though. (Unless Microsoft means copying the data after locking them)

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_device.cpp]: I can't think of a function that allows D3DPOOL_SCRATCH to be copied.

Neither UpdateTexture nor UpdateSurface allow it.

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp]: I guess that's fine then. Got any source on the readonly only for managed thing?

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_device.cpp]: The same reason for D3DPOOL_SCRATCH above

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp]: ?

SystemMem texture can be accessed by the D3D9 device and used for copying. That's the whole issue here. Why wouldn't games be able to tell the driver that they're just gonna read from it?

Comment (Joshua-Ashton) [reply src/d3d9/d3d9_device.cpp]: We're talking about managed here?

Comment (K0bin) [reply src/d3d9/d3d9_device.cpp]: Discussion resolved on Discord
